version: '3.1'
services:
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper

  mysql:
    image: mysql:5.7
    ports: 
      - "3306:3306"
    container_name: mysql-docker
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: Root@123
      MYSQL_DATABASE: booking_service
      
  spring:
    image: spring-boot-sql
    build: bookng-service/
    restart: always
    network_mode: host
    container_name: spring-docker
    depends_on: 
      - mysql
    ports: 
      - 9090:9090
    expose: 
      - 9090











